### ISSUE TITLE
Any ideas what this error means:  Waited the max PT1M waiting on indexing results to come back documentReceivedCount=xxxxxxx, deleteReceivedCount=0, indexedResultCount=xxxxxxx. Everything is done so crawl being marked as completed now. But this may result in documents being missed.

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#143]
At the end of a crawl, I get this error in the logs:

Waited the max PT1M waiting on indexing results to come back documentReceivedCount=375532, deleteReceivedCount=0, indexedResultCount=375518. Everything is done so crawl being marked as completed now. But this may result in documents being missed.

Any ideas?

**Comment by roblucar** [comment]
Hi @eborisowIQVIA , I confirmed this log output and code path is only present on 5.4.5 patch branch. The released versions will not have this error.
