### ISSUE TITLE
ContentFetcher postFetch() is never called

### ISSUE THREAD

**Issue by fb-ben** [lucidworks/connectors-sdk-resources#17]
Hello, I am writing a connector and I am having some issues with the ContentFetcher.
The postFetch method is never called and the fetched objects never seem to be marked as complete.
When the job runs the first time, the preFetch() emits the items and they are fetched as expected.
When the job runs the second time, the preFetch() emits no items (as expected as there is no new content in my case), however, all of the previous items are fetched again as they appear to be incomplete.

So my questions are:
1. Am I missing something to mark these items as complete so they won't be indexed again until the preFetch() emits them again?
2. Is there something specific I need to do to get the postFetch() function to be called?
3. Is the fact postFetch() is never called the reason these objects are never marked as complete and indexed every time the job runs?

Thanks.

**Comment by mwmitchell** [comment]
Hi @fb-ben,

Can you provide the version of Fusion you're using? If at all possible, can you share code snippets?

Could you also describe what it is that your postFetch method is doing? It sounds like you could probably just store metadata on the items (last-modified or similar), then when the framework sends back during the re-crawl, your connector would have to use the metadata stored in each item, and compare to the most up-to-date metadata for each item. If the new last-modified is greater than what was stored during the last crawl, you'd want to then re-fetch the content.

As far as why the postFetch is not being called -- this may be a bug, but I believe you will be Ok without it. We'll have a look at this and fix if that's the case.

**Comment by fb-ben** [comment]
I am using version 4.1.0 of fusion.

Ideally, I want only items emitted in the preFetch phase to be (re-)indexed to avoid unnecessary load on the source system. For our preFetch, we query for any items that require indexing and emit them as candidates when should then be fetched when fetch() is called.

I've tried to skip any items that weren't emitted in the preFetch phase, but it never would update the metadata when the item was re-emitted, it retained it's old metadata from the first emitCandidate call.

Is there anyway to mark these objects as complete so they won't be re-fetched until they are re-emitted again? I've tried calling emitCheckpoint() and whatever else but nothing seemed to make a difference.
Was fusion just not designed to work in the way I am trying to get it to work?
My fetch function looks like this

public FetchResult fetch(FetchContext fetchContext)
    {
    // Gather metadata content from source
    // InputStream contentInputStream
    // Map<String, Object> properties
   if (contentInputStream != null)
        {
        Supplier<InputStream> supplier = () -> contentInputStream;
        fetchContext.emitContent(supplier, properties);
        }
      else
        fetchContext.emitDocument(properties);
    return fetchContext.newResult();
    }

At the end I emitContent if I have it, otherwise I just emitDocument. Am I missing anything here or is this pretty much what is expected?

Since postFetch wasn't being called I moved the code I needed into the stop method and that seems to work fine.

Thanks for the help on this.

**Comment by roblucar** [comment]
Hi @fb-ben
From the description above, it looks like you are trying to implement incremental re-crawls. In that process just new, modified and deleted items will be retrieved and re-indexed, no need to evaluate all items indexed previously to find out if they changed or not. Implement this type of re-crawl is possible when a Changes API is available(a place where we can retrieve new/modified/deleted items from). Usually the Changes API needs some input: a date, a timestamp, deltaToken, etc. The connectors-sdk framework supports this type re-crawl. 
### Incremental re-crawl requirements
To implement an inc. recrawl it's necessary to use transient items and checkpoints. A transient item is a candidate that will be emitted from the `fetch()` implementation, e.g.
```
context.emitCandidate(itemId, itemFields, itemMetadata, true);
```
The last parameter is the flag(`true` to mark the candidate as transient). The life span of a transient item is the current job. After a transient item is completed, it will be deleted from the crawl database(not from the Index, you can still find that item when perform search). When implementing inc. recrawls, it's necessary to mark all candidates as transient items.
For checkpoints, this item won't be indexed, it is useful just as a transport between jobs, to store whatever is necessary to query the Changes API. It's possible to store different data types in the checkpoint metadata and emit multiple checkpoints as well. Every emitted checkpoint should be emitted again, in the future jobs, with the same ID. The metadata can change or not.
### Fetcher implementation template
Example of inc. re-crawl fetcher implementation
```
  // main method, it will receive all items to be processed in the current job
  public FetchResult fetch(FetchContext context) {
    FetchInput fetchInput = context.getFetchInput();
    // find out what's the input type
    Type msgType = fetchInput.getMetadata().get("type");
    switch (msgType) {
      case INITIAL:
        emitInitialItems(FetchContext context);
        break;
      case CHECKPOINT:
        handleCheckpoint(fetchInput, context);
        break;
      case ITEM:
        handleItem(fetchInput, context);
        break;
    }
   // important: every call to fetch(), must return a FetchResult.
   return context.newResult();
  }
  //emits the initial items
  private void emitInitialItems(FetchContext context) {
   // mark the candidate as transient
    initialItems.foreach(item -> context.emitCandidate(initialItemId, itemFields, itemMetadata, true));
  }
  // this method will call the Changes API and get the new/modified/deleted items
  private void handleCheckpoint(FetchInput checkpoint, FetchContext context) {
    String changesApiInput = checkpoint.getMetadata().get("changes-api-input");//we can store necessary information for the ChangesAPI in the metadata map
    while(ChangesAPI.hasChanges(changesApiInput)) {
      List<Changes> changes = ChangesAPI.getchanges(changesApiInput);
      changes.forEach(updatedItem -> context.emitCandidate(itemId, itemFields, itemMetadata, true));
    }
    //after all changes were retrieved, update the checkpoint
    context.emitCheckpoint(checkpoint.getId(), newCheckpointMetadata);
  }
  private void handleItem(FetchContext context) {
    context.emitDocument(itemId, itemFields, itemMetadata));
    //or content
    context.emitContent(itemId, inputStream, itemFields, itemMetadata));
  }
```
### Incremental re-crawl notes: 
- Transient items will be removed from the crawl database when a FetchResult for that item is emitted from the `fetcher()` method.
- At the end of each job, just the checkpoints will be persisted in the crawl database.
- For the first job, the initial items will be emitted as transient candidates, those candidates will be processed in later calls to the `fetch()` method. Those new calls will emit contents or documents. This is how the job starts.
- Starting from the second job, the initial items will be the checkpoints. Fetcher implementation is responsible to detect the checkpoints and emit transient candidates, this is how the inc. re-crawl starts, using just the new/modified/deleted items.
Hope this information would be helpful
Thanks,
Lucidworks DAS

**Comment by fb-ben** [comment]
Thank you Robert, this helped a lot.
