### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#22]
Is there any Javadoc-style documentation available?

For example, for com.lucidworks.fusion.connector.plugin.api.fetcher.type.content.MessageHelper, what are the parameters for the method expecting?  There is the id, a Map for fields and a Map for Metadata?  Is there some reference for the values expected?

**Comment by mwmitchell** [comment]
Hi @eborisowIQVIA! Which version of Fusion are you working with?

**Comment by eborisowIQVIA** [comment]
It's 4.1.

**Comment by mwmitchell** [comment]
Thanks for your patience, @eborisowIQVIA. The 4.1 documentation is here: https://doc.lucidworks.com/fusion-connector-javadocs/4.1/ -- the docs do say "4.1.0-SNAPSHOT" but they are indeed 4.1.0.

**Comment by mwmitchell** [comment]
Closing this one, but feel free to file another issue if needed!
