### ISSUE TITLE
When to use pre-fetch vs fetch?

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#23]
Can someone describe when to use the preFetch method vs. fetch?

**Comment by roblucar** [comment]
The preFetch methods are used when you only want to emit candidates and not actual documents or content to be indexed. Prefetch is useful if you want to get crawl statistics of the target source before crawling the actual content.

**Comment by eborisowIQVIA** [comment]
Thank you, @roblucar.
