### ISSUE TITLE
Compatible APIs

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#25]
Hi everyone,

For a connector, I would like to use the Spring Framework libraries (e.g. RestTemplate).  It seems that some versions are not compatible.  Is there any list or any guidance on compatibility with other libraries?

Thanks!

**Comment by mwmitchell** [comment]
@eborisowIQVIA - is this still an issue for you? As far as I know, there should not be any restrictions with using 3rd party libraries within a custom connector (if there is, it's going to be a bug). If you want to use spring and hook into its DI framework, there are ways to make that work too. You should be able to add any needed dependencies to your `build.gradle` file, build/assemble and inspect the jar/zip produced to ensure those libraries made it into the final output artifact.

**Comment by eborisowIQVIA** [comment]
Fusion seemed to cause problems with newer versions of Spring.  I decided to go with Spring 4.3.20.RELEASE and it seems to be working ok.
