### ISSUE TITLE
Issue with number of documents created

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#28]
Hi,

I've created my own connector but something is wrong with the number of items that get created.  The source system has around 1,700 but, as you can see, over 6,000 documents are getting created.  I'm basically just creating a document emitter and emitting it during fetch.

com.lucidworks.fusion.connector.plugin.api.fetcher.type.content.Content.Emitter newEmittedDoc = fetchContext.newContent(asset.getId(), streamSupplier);
newEmittedDoc.withFields(fields);
newEmittedDoc.emit();

Any thoughts of why I would get so many?

Thanks!

**Comment by eborisowIQVIA** [comment]
![fetch-numbers](https://user-images.githubusercontent.com/42912027/55439664-52c8c480-5573-11e9-8800-d08a3e695ad2.png)
Forgot the attachment.

**Comment by mwmitchell** [comment]
Hi @eborisowIQVIA - it is possible that the content you are emitting is being parsed by Fusion, which then results in additional documents. Can you have a look at the documents and see if there are some that have this prefix: `_lw_parser_`?

**Comment by eborisowIQVIA** [comment]
Thanks, @mwmitchell.  Yes, they do have those fields populated.
![parser](https://user-images.githubusercontent.com/42912027/55690537-f0036e80-5960-11e9-9d0a-c475f177e18b.png)

**Comment by eborisowIQVIA** [comment]
Also, if I facet on the type, this is what I get...
![parser_type](https://user-images.githubusercontent.com/42912027/55690571-4cff2480-5961-11e9-8018-a787f48eebf8.png)

**Comment by eborisowIQVIA** [comment]
@mwmitchell - It looks like the parser is extracting things like PowerPoint documents into multiple items.  Any way to prevent that?
![ppt](https://user-images.githubusercontent.com/42912027/55696566-9e240e00-598b-11e9-8da5-ca40404391c0.png)

**Comment by mwmitchell** [comment]
Hi @eborisowIQVIA - thanks for those details, and yes, that is indeed what's happening.

Depending on what you want indexed, you can login into the Fusion Admin UI, find the parser being used (based on the `parserId` field in your connector config), then make changes as needed. You can also use just the API to test your parser configurations, without indexing documents. Here's an example using the built-in `_system` parser:

```
curl -H 'content-type: application/vnd.ms-powerpoint' -X POST 'http://localhost:8765/api/parsers/_system/parse?limit=10' --data-binary @test.pptx
```

Hope that helps!
- Matt

**Comment by mwmitchell** [comment]
Were you able to find a solution to this issue @eborisowIQVIA? If not, we can have a look and possibly suggest a few things to try.

**Comment by mwmitchell** [comment]
Closing this one for now - please feel free to reopen, or file a new issue if needed @eborisowIQVIA
