### ISSUE TITLE
Formatting Error - gradlew command

### ISSUE THREAD

**Issue by jamespoindexter** [lucidworks/connectors-sdk-resources#30]
In README.asciidoc, one of the commands has a couple of formatting errors.

`../gradlew clean build :assemblePlugin`

SHOULD BE 

`./gradlew clean build :assemblePlugins`

**Comment by mwmitchell** [comment]
Yes, thanks for reporting!

**Comment by acesar** [comment]
Fix the gradle commands in https://github.com/lucidworks/connectors-sdk-resources/pull/39
