### ISSUE TITLE
Examples of using the persistent store?

### ISSUE THREAD

**Issue by erikgui** [lucidworks/connectors-sdk-resources#7]
Hello,
I am trying to migrate my connectors for Phabricator written previously for fusion 3.0 that uses the crawlDB. Is it possible to add an example on how to use the new distributed data store or crawlDB?
Thanks!

**Comment by erikgui** [comment]
I have tried moving the previous implementation over using `org.mapdb.DB`. However, I can't seem to resolve this import: `import com.lucidworks.Constants;` which is used to create the crawlDB file.

**Comment by mwmitchell** [comment]
Hi @erikgui,

The crawl-db in this new version of Connectors is mostly handled for you, and is managed by Fusion. When you deploy a Connector (either embedded as a BlobStore plugin or as a remote client), Fusion will recognize and register your Connector. If the Connector is valid, the DataSource/IndexWorkbench UIs in the Fusion admin will then allow you to create configurations (Datasources) for your plugin, and subsequently run crawls/jobs.

Once a job for your plugin/config is started, Fusion will then allocate a new Collection per-configuration, which is a dedicated crawl-db. Currently, this crawl-db is designed for true "crawling" (fetch, discover candidates, re-fetch, repeat etc.). The mechanism for getting this all to work can be seen (generally) in the [RandomContentFetcher](https://github.com/lucidworks/connectors-sdk-resources/blob/master/java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java) example.

The upcoming Fusion 4.1 release will also include checkpointing capability. This will be useful for Connectors that do sequential fetching against a REST API or SQL source etc., for example. The checkpoint keeps track of where you're at in the fetch process, so that subsequent jobs will pickup where the previous job stopped.

Hope this helps! Feel free to share more details of what you'd like to accomplish and we'll do our best to help you out.

**Comment by erikgui** [comment]
Thank you for your detailed explanation @mwmitchell! 

Previously in my code, the crawl-db was being used for keeping track if a given document has been updated or not during re-fetches by explicitly comparing the dateModified field in the JSON response. 

In this version, as long as we emit the document metadata during pre-fetch, then this check would automatically be handled?

Thanks again for your help!

**Comment by erikgui** [comment]
Hey @mwmitchell,
Thanks for the clarification! I would love to see an example of the comparison you mentioned above. How would I get the "live source item's dateModified"? Could you please help me with filling the ???'s below?

Here's what I have in mind:
```
  @Override
  public FetchResult fetch(FetchContext fetchContext) {
    FetchInput input = fetchContext.getFetchInput();
    Map<String, Object> fields = input.getFields();
    if (fields.get("dateModified").equals(/* ??? */)) {
      fetchContext.emitSkip(/* ??? */);
    } else {
      fetchContext.emitDocument(input.getFields());
    }
    return fetchContext.newResult();
  }
```
I am not sure what format the `conditions` set should be.

Thanks for your help!

**Comment by mwmitchell** [comment]
Hi @erikgui,

Great questions! The "conditions" are mainly diagnostic at this point. They are the "reasons" a certain item was skipped. The "live source" is basically where the data is coming from, like a repository or file system. So the metadata from the source could be compared against what's passed to the fetcher, which would be the item from the last fetch. Here's a modified version of your code + comments:

```java
@Override
public FetchResult fetch(FetchContext fetchContext) {
  FetchInput input = fetchContext.getFetchInput();
  if( input.getId() == null ){
    // Currently, we signal a new/initial fetch call by sending an input with a null id value to the fetcher.
    // This happens only on the very first fetch call for a Connector that has no crawl-db state,
    // and where you'd normally emit the first set of "candidates".
    // Candidates are emitted, processed by Fusion, and are then eventually resent to all fetchers in a distributed manner (round-robin).
    // So here, we'll fetch all of the "root items" from some source API, and emit as Candidates.
    // The data attached to the Candidate objects is mostly the "id", but can include other metadata
    // in case the actual fetch call (which happens later) for any of these items requires special context (the metadata).
    // This whole process is easy to distribute, but it's critical that the process of gathering Candidate
    // metadata is "cheap" - if the call to the source for these items is expensive
    // (input streams are read etc.), then it would make more sense to simply emit these items as
    // Documents, which are processed by Fusion and pretty much
    // immediately indexed to Solr as "content".
    // But we'll assume we have a source that gives us good metadata without a lot of overhead.
    getRootItems().forEach(item -> {
      // These items are streamed back to Fusion, and immediately distributed to all fetchers.
      // So while this loop is running, it is very possible that other nodes (or "this" node) begin fetching the items before this loop completes.
      Thing src = source.findById(item.getId());
      fetchContext.emitCandidate( createCandidateFromItemWithLastModifiedField(src.getId(), src.getLastModifiedDate()) );
    });
    // Return - we're done with the initial fetch call...
    return fetchContext.newResult();
  }
  
  // Here is where we're dealing with an item that was previously emitted as a Candidate.
  // The main idea is that a fetcher emits minimal metadata for each item, then Fusion receives the items, saves them in the "crawl-db", and re-distributes to parallelize the fetching process.
  // By calling getFields(), we're assuming that the Candidate that was previously emitted for this item
  // was populated with "fields" via the method createCandidateFromItemWithLastModifiedField, referenced above.
  Map<String, Object> fields = input.getFields();
  String id = (String) fields.get("id");
  // Below, the "current" object is coming from a "source".
  // This could be a filesystem backed source, something backed by a SQL DB, or even API.
  // But it's essentially coming from the same place that our createCandidateFromItemWithLastModifiedField method got its data from.
  // And ideally, this source object would return metadata only (not full content), and be relatively inexpensive to call.
  Thing current = source.findById(id);
  if ( ((Long)fields.get("dateModified")) == current.getLastModified() ) {
    // Nothing has changed, let's emit a "skip" and record a simple String/tag to help indicate why.
    fetchContext.emitSkip(Sets.newHashSet("not-modified"));
    // Note that any "skip" item is re-fetched in later crawls. So if the items changes, and then you re-crawl this Connector - the item will be re-sent to a fetcher so that the latest content can be fetched/indexed.
  } else {
    // Here is where an item has been identified as "changed", and therefore needs to be re-fetched.
    // In most cases, this is where you'd want to handle a more "expensive" content process, possibly parsing content, a complex SQL join, or maybe multiple API calls to compose the final output for a "document".
    fetchContext.emitDocument( composeDocument(current) );
  }
  return fetchContext.newResult();
}
```

**Comment by mwmitchell** [comment]
A lot of code comments I left there! Don't hesitate to ask more questions though. Would be happy to provide an example if I can get some time this week.

**Comment by erikgui** [comment]
@mwmitchell Thank you so much for your extremely detailed explanation! Thank you so much for this example! This has been a tremendous help for me to understand how to implement my custom connector. I am very grateful to have received such attention and assistance from you!
