### ISSUE TITLE
Schema Annotation for Secrets in Plugin Configuration

### ISSUE THREAD

**Issue by tsuyoshihamano** [lucidworks/connectors-sdk-resources#94]
Hi, Tsuyoshi from Raytion GmbH here. 
Is there a Schema Annotation provided by your Connector SDK v.3.0.0 which marks a property as a secret value. 
I am expecting the annotated property to be shown hidden in the Datasource Configuration of the Admin UI. 

Thank you in advance. 
Tsuyoshi

**Comment by mwmitchell** [comment]
Hi @tsuyoshihamano. You can apply the "hints" attribute + `SECRET` to a `@Property` annotation, something like this:

```java
package foo;

import com.lucidworks.fusion.schema.Model;
import com.lucidworks.fusion.schema.SchemaAnnotations.Property;
import com.lucidworks.fusion.schema.SchemaAnnotations.StringSchema;
import com.lucidworks.fusion.schema.UIHints;

interface MyConfig extends Model {
  
  @Property(title = "My Property",
    description = "...",
    hints = {UIHints.SECRET}
  )
  @StringSchema()
  String myProperty();
  
}
```

**Comment by tsuyoshihamano** [comment]
Thanks. Works perfectly.
