### ISSUE TITLE
Different behavior when running with connectorPluginClient

### ISSUE THREAD

**Issue by anghelutar** [lucidworks/connectors-sdk-resources#96]
Hi,

My custom connector runs fine when deployed on the Fusion instance, however when I run it using the connector plugin client it throws the following errors:

Caused by: io.grpc.StatusRuntimeException: UNKNOWN: java.lang.IllegalAccessException: Unable to create injector, see the following errors:

_1) An exception was caught and reported. Message: java.lang.RuntimeException: java.lang.IllegalAccessException: access to public member failed: com.lucidworks.fusion.connector.plugin.api.config.ConnectorConfig.schematize[Ljava.lang.Object;@4ca83faa/invokeSpecial, from com.lucidworks.fusion.connector.plugin.api.config.ConnectorConfig/2 (unnamed module @36ef1d65)
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for com.lucidworks.fusion.connector.plugin.api.config.ConnectorConfig was bound.
  at com.lucidworks.fusion.connector.plugin.ext.controller.FetchManagerRegistry$1.configure(FetchManagerRegistry.java:71)_

I am not sure where is the issue and how to debug, can you give me some pointers please?

Thanks,
Roxana

**Comment by puneetkhanal** [comment]
Hi,

What is the fusion version?

**Comment by acesar** [comment]
@anghelutar what is the java version you are using?

**Comment by anghelutar** [comment]
Java 11 locally and java 8 on Fusion :-)
Thanks!
